language: python
python:
  - "3.4"

services:
  - mysql
  - git

before_install:
  - git clone https://github.com/lodevil/Lo-runner.git
  - cd Lo-runner && sudo ./setup.py build && sudo ./setup.py install
  - cd ..

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py check

# after_success: 
#   - bash <(curl -s https://codecov.io/bash)